In [1]:
import pandas as pd

In [2]:
pwd

'C:\\Users\\acer'

In [3]:
cd C:\\Users\\acer\\Downloads

C:\Users\acer\Downloads

In [4]:
df1 = pd.read_excel("920010072464939.xls")[15:26]
df1 = df1.rename(columns=df1.iloc[0]).drop(df1.index[0]).reset_index(drop=True)
df1

,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
0,1,31-03-2021,-,920010072464939:Int.Pd:01-01-2021 to 31-03-2021,,107.00,14547.10,2854
1,2,18-04-2021,-,GST @18% on Charge,2.70,,14544.40,2854
2,3,18-04-2021,-,Consolidated Charges for A/c,15.00,,14529.40,2854
3,4,01-07-2021,-,920010072464939:Int.Pd:01-04-2021 to 30-06-2021,,109.00,14638.40,2854
4,5,18-07-2021,-,GST @18% on Charge,2.70,,14635.70,2854
5,6,18-07-2021,-,Consolidated Charges for A/c,15.00,,14620.70,2854
6,7,01-10-2021,-,920010072464939:Int.Pd:01-07-2021 to 30-09-2021,,111.00,14731.70,2854
7,8,30-11-2021,-,ATM-CASH-AXIS/DPCN166408/5664/301121/PATNA,5000.00,,9731.70,2854
8,9,13-12-2021,-,Dr Card Charges ANNUAL 4616XXXXXXXX6139,590.00,,9141.70,2854
9,10,01-01-2022,-,920010072464939:Int.Pd:01-10-2021 to 31-12-2021,,97.00,9238.70,2854

In [5]:
df2 = pd.read_excel("920010072464939 (1).xls")[15:45]
df2 = df2.rename(columns=df2.iloc[0]).drop(df2.index[0]).reset_index(drop=True)
df2

,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
0,1,13-02-2022,-,GST @18% on Charge,19.17,,9219.53,2854
1,2,13-02-2022,-,Consolidated Charges for A/c,106.50,,9113.03,2854
2,3,20-03-2022,-,GST @18% on Charge,20.36,,9092.67,2854
3,4,20-03-2022,-,Consolidated Charges for A/c,113.10,,8979.57,2854
4,5,31-03-2022,-,920010072464939:Int.Pd:01-01-2022 to 31-03-2022,,68.00,9047.57,2854
5,6,17-04-2022,-,GST @18% on Charge,21.01,,9026.56,2854
6,7,17-04-2022,-,Consolidated Charges for A/c,116.70,,8909.86,2854
7,8,21-05-2022,-,GST @18% on MAB Charge,21.93,,8887.93,2854
8,9,21-05-2022,-,Monthly Service Fee 05-2022,121.85,,8766.08,2854
9,10,11-06-2022,-,GST @18% on MAB Charge,40.65,,8725.43,2854
10,11,11-06-2022,-,Monthly Service Fee 06-2022,225.85,,8499.58,2854
11,12,01-07-2022,-,920010072464939:Int.Pd:01-04-2022 to 30-06-2022,,66.00,8565.58,2854
12,13,16-07-2022,-,GST @18% on MAB Charge,41.78,,8523.80,2854
13,14,16-07-2022,-,Monthly Service Fee 07-2022,232.10,,8291.70,2854
14,15,20-08-2022,-,GST @18% on MAB Charge,46.06,,8245.64,2854
15,16,20-08-2022,-,Monthly Service Fee 08-2022,255.90,,7989.74,2854
16,17,15-09-2022,-,GST @18% on MAB Charge,48.28,,7941.46,2854
17,18,15-09-2022,-,Monthly Service Fee 09-2022,268.20,,7673.26,2854
18,19,01-10-2022,-,920010072464939:Int.Pd:01-07-2022 to 30-09-2022,,62.00,7735.26,2854
19,20,12-10-2022,-,GST @18% on MAB Charge,51.65,,7683.61,2854
20,21,12-10-2022,-,Monthly Service Fee 10-2022,286.95,,7396.66,2854
21,22,13-11-2022,-,GST @18% on MAB Charge,56.43,,7340.23,2854
22,23,13-11-2022,-,Monthly Service Fee 11-2022,313.50,,7026.73,2854
23,24,06-12-2022,-,Dr Card Charges ANNUAL 4616XXXXXXXX6139,590.00,,6436.73,2854
24,25,09-12-2022,-,GST @18% on MAB Charge,60.53,,6376.20,2854
25,26,09-12-2022,-,Monthly Service Fee 12-2022,336.30,,6039.90,2854
26,27,01-01-2023,-,920010072464939:Int.Pd:01-10-2022 to 31-12-2022,,53.00,6092.90,2854
27,28,11-01-2023,-,Monthly Service Fee 01-2023,361.95,,5730.95,2854
28,29,11-01-2023,-,GST @18% on MAB Charge,65.15,,5665.80,2854

In [6]:
df3 = pd.read_excel("920010072464939 (2).xls")[15:49]
df3 = df3.rename(columns=df3.iloc[0]).drop(df3.index[0]).reset_index(drop=True)
df3

,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
0,1,10-02-2023,-,GST @18% on MAB Charge,77.80,,5588.00,2854
1,2,10-02-2023,-,Non-Maint Avg bal chgs Dec2022,432.23,,5155.77,2854
2,3,11-03-2023,-,GST @18% on MAB Charge,83.66,,5072.11,2854
3,4,11-03-2023,-,Non-Maint Avg bal chgs Jan2023,464.78,,4607.33,2854
4,5,31-03-2023,-,920010072464939:Int.Pd:01-01-2023 to 31-03-2023,,39.00,4646.33,2854
5,6,12-04-2023,-,GST @18% on MAB Charge,90.19,,4556.14,2854
6,7,12-04-2023,-,Non-Maint Avg bal chgs Feb2023,501.08,,4055.06,2854
7,8,13-05-2023,-,GST @18% on MAB Charge,97.40,,3957.66,2854
8,9,13-05-2023,-,Non-Maint Avg bal chgs Mar2023,541.13,,3416.53,2854
9,10,09-06-2023,-,GST @18% on MAB Charge,83.47,,3333.06,2854
10,11,09-06-2023,-,Non-Maint Avg bal chgs Apr2023,463.74,,2869.32,2854
11,12,01-07-2023,-,920010072464939:Int.Pd:01-04-2023 to 30-06-2023,,27.00,2896.32,2854
12,13,18-07-2023,-,GST @18% on MAB Charge,90.04,,2806.28,2854
13,14,18-07-2023,-,Non-Maint Avg bal chgs May2023,500.22,,2306.06,2854
14,15,18-08-2023,-,GST @18% on MAB Charge,97.03,,2209.03,2854
15,16,18-08-2023,-,Non-Maint Avg bal chgs Jun2023,539.04,,1669.99,2854
16,17,09-09-2023,-,GST @18% on MAB Charge,101.21,,1568.78,2854
17,18,09-09-2023,-,Non-Maint Avg bal chgs Jul2023,562.26,,1006.52,2854
18,19,01-10-2023,-,920010072464939:Int.Pd:01-07-2023 to 30-09-2023,,15.00,1021.52,2854
19,20,11-10-2023,-,UPI/P2A/328460409073/FAISAL RA/HDFC BANK/UPI/,,1000.00,2021.52,2854
20,21,11-10-2023,-,GST @18% on MAB Charge,107.81,,1913.71,2854
21,22,11-10-2023,-,Non-Maint Avg bal chgs Aug2023,598.92,,1314.79,2854
22,23,18-10-2023,-,UPI/P2A/329113433524/FAISAL RA/HDFC BANK/UPI/,,500.00,1814.79,2854
23,24,01-11-2023,-,Dr Card Charges ISSUE 4364XXXXXXXX2983,1770.00,,44.79,2854
24,25,25-11-2023,-,UPI/P2A/332925858932/FAISAL RA/HDFC BANK/UPI/,,600.00,644.79,2854
25,26,25-11-2023,-,ECOM PUR/BOOK MY SHOW/BANGALORE/251123/17:22,575.84,,68.95,2854
26,27,27-11-2023,-,GST @18% on MAB Charge,10.52,,58.43,2854
27,28,27-11-2023,-,Non-Maint Avg bal chgs Sep2023,58.43,,.00,2854
28,29,30-12-2023,-,UPI/P2A/336575151920/FAISAL RA/HDFC BANK/UPI/,,800.00,800.00,2854
29,30,30-12-2023,-,ECOM PUR/Bookmyshow/400049/301223/18:41/336418...,794.60,,5.40,2854
30,31,01-01-2024,-,920010072464939:Int.Pd:01-10-2023 to 31-12-2023,,4.00,9.40,2854
31,32,21-01-2024,-,SMS Alerts Chrgs Incl GST,1.48,,7.92,2854
32,33,21-01-2024,-,POS Decline Chrgs Incl GST,7.92,,.00,2854

In [7]:
df = pd.concat([df1,df2,df3]).reset_index()
df

,index,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
0,0,1,31-03-2021,-,920010072464939:Int.Pd:01-01-2021 to 31-03-2021,,107.00,14547.10,2854
1,1,2,18-04-2021,-,GST @18% on Charge,2.70,,14544.40,2854
2,2,3,18-04-2021,-,Consolidated Charges for A/c,15.00,,14529.40,2854
3,3,4,01-07-2021,-,920010072464939:Int.Pd:01-04-2021 to 30-06-2021,,109.00,14638.40,2854
4,4,5,18-07-2021,-,GST @18% on Charge,2.70,,14635.70,2854
...,...,...,...,...,...,...,...,...,...
67,28,29,30-12-2023,-,UPI/P2A/336575151920/FAISAL RA/HDFC BANK/UPI/,,800.00,800.00,2854
68,29,30,30-12-2023,-,ECOM PUR/Bookmyshow/400049/301223/18:41/336418...,794.60,,5.40,2854
69,30,31,01-01-2024,-,920010072464939:Int.Pd:01-10-2023 to 31-12-2023,,4.00,9.40,2854
70,31,32,21-01-2024,-,SMS Alerts Chrgs Incl GST,1.48,,7.92,2854
71,32,33,21-01-2024,-,POS Decline Chrgs Incl GST,7.92,,.00,2854

In [8]:
df['DR'] = pd.to_numeric(df['DR'], errors='coerce')
df['CR'] = pd.to_numeric(df['CR'], errors='coerce')

In [9]:
df[df['PARTICULARS'].str.contains('Consolidated Charges for A/c')]

,index,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
2,2,3,18-04-2021,-,Consolidated Charges for A/c,15.0,NaN,14529.40,2854
5,5,6,18-07-2021,-,Consolidated Charges for A/c,15.0,NaN,14620.70,2854
11,1,2,13-02-2022,-,Consolidated Charges for A/c,106.5,NaN,9113.03,2854
13,3,4,20-03-2022,-,Consolidated Charges for A/c,113.1,NaN,8979.57,2854
16,6,7,17-04-2022,-,Consolidated Charges for A/c,116.7,NaN,8909.86,2854

In [10]:
df[df['PARTICULARS'].str.contains('Consolidated Charges for A/c')]['DR'].sum()

366.3

In [11]:
df[df['PARTICULARS'].str.contains('Dr Card Charges')]

,index,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
8,8,9,13-12-2021,-,Dr Card Charges ANNUAL 4616XXXXXXXX6139,590.0,NaN,9141.70,2854
33,23,24,06-12-2022,-,Dr Card Charges ANNUAL 4616XXXXXXXX6139,590.0,NaN,6436.73,2854
62,23,24,01-11-2023,-,Dr Card Charges ISSUE 4364XXXXXXXX2983,1770.0,NaN,44.79,2854

In [12]:
df[df['PARTICULARS'].str.contains('Dr Card Charges')]['DR'].sum()

2950.0

In [13]:
df[df['PARTICULARS'].str.contains(':Int.Pd:')]

,index,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
0,0,1,31-03-2021,-,920010072464939:Int.Pd:01-01-2021 to 31-03-2021,NaN,107.0,14547.10,2854
3,3,4,01-07-2021,-,920010072464939:Int.Pd:01-04-2021 to 30-06-2021,NaN,109.0,14638.40,2854
6,6,7,01-10-2021,-,920010072464939:Int.Pd:01-07-2021 to 30-09-2021,NaN,111.0,14731.70,2854
9,9,10,01-01-2022,-,920010072464939:Int.Pd:01-10-2021 to 31-12-2021,NaN,97.0,9238.70,2854
14,4,5,31-03-2022,-,920010072464939:Int.Pd:01-01-2022 to 31-03-2022,NaN,68.0,9047.57,2854
21,11,12,01-07-2022,-,920010072464939:Int.Pd:01-04-2022 to 30-06-2022,NaN,66.0,8565.58,2854
28,18,19,01-10-2022,-,920010072464939:Int.Pd:01-07-2022 to 30-09-2022,NaN,62.0,7735.26,2854
36,26,27,01-01-2023,-,920010072464939:Int.Pd:01-10-2022 to 31-12-2022,NaN,53.0,6092.90,2854
43,4,5,31-03-2023,-,920010072464939:Int.Pd:01-01-2023 to 31-03-2023,NaN,39.0,4646.33,2854
50,11,12,01-07-2023,-,920010072464939:Int.Pd:01-04-2023 to 30-06-2023,NaN,27.0,2896.32,2854
57,18,19,01-10-2023,-,920010072464939:Int.Pd:01-07-2023 to 30-09-2023,NaN,15.0,1021.52,2854
69,30,31,01-01-2024,-,920010072464939:Int.Pd:01-10-2023 to 31-12-2023,NaN,4.0,9.40,2854

In [14]:
df[df['PARTICULARS'].str.contains(':Int.Pd:')]["CR"].sum()

758.0

In [15]:
df[df['PARTICULARS'].str.contains('Non-Maint Avg bal chgs')]

,index,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
40,1,2,10-02-2023,-,Non-Maint Avg bal chgs Dec2022,432.23,NaN,5155.77,2854
42,3,4,11-03-2023,-,Non-Maint Avg bal chgs Jan2023,464.78,NaN,4607.33,2854
45,6,7,12-04-2023,-,Non-Maint Avg bal chgs Feb2023,501.08,NaN,4055.06,2854
47,8,9,13-05-2023,-,Non-Maint Avg bal chgs Mar2023,541.13,NaN,3416.53,2854
49,10,11,09-06-2023,-,Non-Maint Avg bal chgs Apr2023,463.74,NaN,2869.32,2854
52,13,14,18-07-2023,-,Non-Maint Avg bal chgs May2023,500.22,NaN,2306.06,2854
54,15,16,18-08-2023,-,Non-Maint Avg bal chgs Jun2023,539.04,NaN,1669.99,2854
56,17,18,09-09-2023,-,Non-Maint Avg bal chgs Jul2023,562.26,NaN,1006.52,2854
60,21,22,11-10-2023,-,Non-Maint Avg bal chgs Aug2023,598.92,NaN,1314.79,2854
66,27,28,27-11-2023,-,Non-Maint Avg bal chgs Sep2023,58.43,NaN,.00,2854

In [16]:
df[df['PARTICULARS'].str.contains('Non-Maint Avg bal chgs')]["DR"].sum()

4661.830000000001

In [17]:
df[df['PARTICULARS'].str.contains('Monthly Service Fee')]

,index,SRL NO,Tran Date,CHQNO,PARTICULARS,DR,CR,BAL,SOL
18,8,9,21-05-2022,-,Monthly Service Fee 05-2022,121.85,NaN,8766.08,2854
20,10,11,11-06-2022,-,Monthly Service Fee 06-2022,225.85,NaN,8499.58,2854
23,13,14,16-07-2022,-,Monthly Service Fee 07-2022,232.10,NaN,8291.70,2854
25,15,16,20-08-2022,-,Monthly Service Fee 08-2022,255.90,NaN,7989.74,2854
27,17,18,15-09-2022,-,Monthly Service Fee 09-2022,268.20,NaN,7673.26,2854
30,20,21,12-10-2022,-,Monthly Service Fee 10-2022,286.95,NaN,7396.66,2854
32,22,23,13-11-2022,-,Monthly Service Fee 11-2022,313.50,NaN,7026.73,2854
35,25,26,09-12-2022,-,Monthly Service Fee 12-2022,336.30,NaN,6039.90,2854
37,27,28,11-01-2023,-,Monthly Service Fee 01-2023,361.95,NaN,5730.95,2854

In [18]:
df[df['PARTICULARS'].str.contains('Monthly Service Fee')]["DR"].sum()

2402.6

In [19]:
df.to_excel("Axis Bank Mini Statement.xlsx")