In [1]:
import pandas as pd

In [19]:
df = pd.read_csv("Pokemon.csv")

In [20]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [11]:
train= df[:80*7]
train

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,496,Servine,Grass,NaN,413,60,60,75,60,75,83,5,False
556,497,Serperior,Grass,NaN,528,75,75,95,75,95,113,5,False
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False

In [14]:
test = df[80*7:]
test

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
560,501,Oshawott,Water,NaN,308,55,55,45,63,45,45,5,False
561,502,Dewott,Water,NaN,413,75,75,60,83,60,60,5,False
562,503,Samurott,Water,NaN,528,95,100,85,108,70,70,5,False
563,504,Patrat,Normal,NaN,255,45,55,39,35,39,42,5,False
564,505,Watchog,Normal,NaN,420,60,85,69,60,69,77,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [25]:
from sklearn.model_selection import train_test_split

In [34]:
x1,x2 = train_test_split(df,test_size= 0.3,random_state=1)

In [35]:
x1

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
88,81,Magnemite,Electric,Steel,325,25,35,70,95,55,45,1,False
107,99,Kingler,Water,NaN,475,55,130,115,50,50,75,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
700,639,Terrakion,Rock,Fighting,580,91,129,90,72,90,108,5,True
172,158,Totodile,Water,NaN,314,50,65,64,44,48,43,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,648,MeloettaAria Forme,Normal,Psychic,600,100,77,77,128,128,90,5,False
767,697,Tyrantrum,Rock,Dragon,521,82,121,119,69,59,71,6,False
72,66,Machop,Fighting,NaN,305,70,80,50,35,35,35,1,False
235,217,Ursaring,Normal,NaN,500,90,130,75,75,75,55,2,False
37,32,Nidoran♂,Poison,NaN,273,46,57,40,40,40,50,1,False

In [31]:
x2

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
745,677,Espurr,Psychic,NaN,355,62,48,54,63,60,68,6,False
115,107,Hitmonchan,Fighting,NaN,455,50,105,79,35,110,76,1,False
173,159,Croconaw,Water,NaN,405,65,80,80,59,63,58,2,False
120,112,Rhydon,Ground,Rock,485,105,130,120,45,45,40,1,False
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
167,153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True
765,695,Heliolisk,Electric,Normal,481,62,55,52,109,94,109,6,False