Find the number which are present in both the list.

In [1]:
l1 = [1,2,3,4,5]
l2 = [4,5,6,7]

In [3]:
[i for i in l2 if i in l1]

[4, 5]

Create a data frame from the dictionary and then. group by category some by cells and average by transaction count.

In [8]:
import random

data = {
    "id": [random.randint(1000, 9999) for _ in range(8)],
    "category": [random.choice(["Electronics", "Clothing", "Home", "Toys", "Books"]) for _ in range(8)],
    "sales": [round(random.uniform(100.5, 9999.99), 2) for _ in range(8)],
    "transaction_count": [random.randint(1, 50) for _ in range(8)],
}

In [10]:
import pandas as pd

In [14]:
df = pd.DataFrame(data)
df

     id     category    sales  transaction_count
0  4769  Electronics  7846.68                 41
1  2169  Electronics  2561.92                 11
2  8640         Toys  1241.66                 45
3  7367        Books  4934.63                 32
4  1988         Home  8278.22                 41
5  9688  Electronics  7684.26                 29
6  9513  Electronics  4694.87                 30
7  1217        Books  1841.74                 16

In [92]:
df.groupby("category").agg({
    "sales": "sum",
    "transaction_count": "mean"
})

                sales  transaction_count
category
Books         6776.37              24.00
Electronics  22787.73              27.75
Home          8278.22              41.00
Toys          1241.66              45.00

given a sequence of number in an array , a=[1,2,4,5,6], find the missing element

In [94]:
a = [1, 2, 4, 5, 6]

# Calculate expected sum
expected_sum = sum(range(min(a), max(a) + 1))

# Calculate actual sum
actual_sum = sum(a)

# The missing number
missing_number = expected_sum - actual_sum

print("Missing number:", missing_number)

Missing number: 3